apiVersion: apps/v1
kind: Deployment
metadata:
  name: visbert-gpu
spec:
  selector:
    matchLabels:
        app: visbert-gpu
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: visbert-gpu
    spec:
      containers:
        - name: visbert-gpu
          image: registry.datexis.com/bvanaken/visbert:v1.1
          command:
            - /bin/sh
            - "-c"
            - "sleep 1h"
          imagePullPolicy: Always
          ports:
            - name: client-port
              containerPort: 1337
          resources:
            limits:
              memory: 12Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: visbert-models-pvc
              mountPath: /models_dir
      nodeSelector:
        gpu: p100
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: visbert-models-pvc
          persistentVolumeClaim:
            claimName: visbert-models-pvc